import StyleDictionary from 'style-dictionary';
import { fileHeader, usesReferences, getReferences } from 'style-dictionary/utils';
import { register } from '@tokens-studio/sd-transforms';
import { logBrokenReferenceLevels, logVerbosityLevels, logWarningLevels } from 'style-dictionary/enums';

// Register Tokens Studio transforms
register(StyleDictionary);

// Convert string to kebab-case
const toKebabCase = str =>
	str
		.replace(/([a-z])([A-Z])/g, '$1-$2')
		.replace(/\./g, '-') // Replace dots with hyphens
		.replace(/\,/g, '-') // Replace commas with hyphens
		.replace(/\s+/g, '-') // Replace spaces with hyphens
		.replace(/-+/g, '-') // Replace multiple consecutive hyphens with single hyphen
		.toLowerCase();

// Register custom file header
StyleDictionary.registerFileHeader({
	name: 'token-header',
	fileHeader: () => {
		return ['Design Tokens - Auto-generated by Style Dictionary', 'Do not edit manually - run `pnpm tokens:build` to regenerate'];
	}
});

// Custom format for CSS variables with theme selector
StyleDictionary.registerFormat({
	name: 'css/variables-themed',
	format: async function ({ dictionary, options, file }) {
		const selector = options.selector || ':root';
		const { outputReferences } = options;

		const tokens = dictionary.allTokens
			.map(token => {
				// Use the full path to create unique names
				const fullPath = token.path.join('.');
				const name = toKebabCase(fullPath);

				if (outputReferences && usesReferences(token.original.value)) {
					const refs = getReferences(token.original.value, dictionary.tokens, { unfilteredTokens: dictionary.unfilteredTokens, warnImmediately: false });
					let value = token.original.value;
					refs.forEach(ref => {
						const refPath = ref.ref || ref.path;
						const refName = toKebabCase(refPath.join('.'));
						value = value.replace(
							`{${refPath.join('.')}}`,
							`var(--${refName})`
						);
					});
					return `  --${name}: ${value};`;
				}

				return `  --${name}: ${token.value};`;
			})
			.join('\n');

		return (await fileHeader({ file })) + `${selector} {\n${tokens}\n}\n`;
	}
});

// Custom format for SCSS mixins (typography and effects)
StyleDictionary.registerFormat({
	name: 'scss/mixins-styles',
	format: async function ({ dictionary, file }) {
		const tokens = dictionary.allTokens;
		const mixins = [];

		tokens.forEach(token => {
			// Use the full path to create unique mixin names
			const fullPath = token.path.join('.');
			const mixinName = toKebabCase(fullPath);

			// Typography tokens (composite values)
			if (token.type === 'typography' && typeof token.value === 'object') {
				const properties = [];
				if (token.value.fontFamily) properties.push(`  font-family: ${token.value.fontFamily};`);
				if (token.value.fontWeight) properties.push(`  font-weight: ${token.value.fontWeight};`);
				if (token.value.fontSize) properties.push(`  font-size: ${token.value.fontSize};`);
				if (token.value.lineHeight) properties.push(`  line-height: ${token.value.lineHeight};`);
				if (token.value.letterSpacing) properties.push(`  letter-spacing: ${token.value.letterSpacing};`);
				if (token.value.textTransform) properties.push(`  text-transform: ${token.value.textTransform};`);
				if (token.value.textDecoration) properties.push(`  text-decoration: ${token.value.textDecoration};`);

				if (properties.length > 0) {
					mixins.push(`@mixin ${mixinName} {\n${properties.join('\n')}\n}`);
				}
			}
			// Shadow tokens
			else if (token.type === 'shadow') {
				mixins.push(`@mixin ${mixinName} {\n  box-shadow: ${token.value};\n}`);
			}
			// Blur tokens
			else if (token.type === 'blur') {
				mixins.push(`@mixin ${mixinName} {\n  filter: blur(${token.value});\n}`);
			}
			// Color tokens (simple variable)
			else if (token.type === 'color') {
				mixins.push(`$${mixinName}: ${token.value};`);
			}
		});

		return (await fileHeader({ file })) + mixins.join('\n\n') + '\n';
	}
});

// Filter to only include tokens from specified source paths
// Matches if filePath contains any of the provided path segments
const semanticFilter =
	(...sourcePaths) =>
	token => {
		if (!token.filePath) return false;
		return sourcePaths.some(path => {
			// Extract base path before any glob patterns
			const basePath = path.split('*')[0].replace(/\/$/, '');
			// For exact file paths (no globs), match the full path
			if (!path.includes('*')) {
				return token.filePath.includes(path);
			}
			// For glob patterns, match the base directory
			return token.filePath.includes(basePath);
		});
	};


// Build configuration for component semantics
const componentsConfig = {
	include: ['tokens/core/**/*.json', 'tokens/semantic/dark.json'],
	source: ['tokens/components/**/*.json'],
	preprocessors: ['tokens-studio'],
	platforms: {
		css: {
			transformGroup: 'tokens-studio',
			buildPath: 'src/assets/styles/style-dictionary/tokens/',
			files: [
				{
					destination: 'component_semantics.css',
					format: 'css/variables-themed',
					filter: semanticFilter('tokens/components/**/*.json'),
					options: {
						selector: 'body',
						outputReferences: true
					}
				}
			],
			options: {
				fileHeader: 'token-header'
			}
		}
	}
};

// Build configuration for dark theme
const darkConfig = {
	include: ['tokens/core/**/*.json'],
	source: ['tokens/semantic/dark.json'],
	preprocessors: ['tokens-studio'],
	platforms: {
		css: {
			transformGroup: 'tokens-studio',
			buildPath: 'src/assets/styles/style-dictionary/tokens/themes/',
			files: [
				{
					destination: 'dark.css',
					format: 'css/variables-themed',
					filter: semanticFilter('tokens/semantic/dark.json'),
					options: {
						selector: 'body[mode="night"]',
						outputReferences: true
					}
				}
			],
			options: {
				fileHeader: 'token-header'
			}
		}
	}
};

// Build configuration for light theme
const lightConfig = {
	include: ['tokens/core/**/*.json'],
	source: ['tokens/semantic/light.json'],
	preprocessors: ['tokens-studio'],
	platforms: {
		css: {
			transformGroup: 'tokens-studio',
			buildPath: 'src/assets/styles/style-dictionary/tokens/themes/',
			files: [
				{
					destination: 'light.css',
					format: 'css/variables-themed',
					filter: semanticFilter('tokens/semantic/light.json'),
					options: {
						selector: 'body[mode="light"]',
						outputReferences: true
					}
				}
			],
			options: {
				fileHeader: 'token-header'
			}
		}
	}
};

// Build configuration for core tokens (shared between themes)
const coreConfig = {
	source: ['tokens/core/**/*.json'],
	preprocessors: ['tokens-studio'],
	platforms: {
		css: {
			transformGroup: 'tokens-studio',
			buildPath: 'src/assets/styles/style-dictionary/tokens/',
			files: [
				{
					destination: 'core.css',
					format: 'css/variables-themed',
					options: {
						selector: ':root'
					}
				}
			],
			options: {
				fileHeader: 'token-header'
			}
		}
	}
};

// Build configuration for styles tokens (shared between themes)
const stylesConfig = {
	include: ['tokens/core/**/*.json'],
	source: ['tokens/styles/**/*.json'],
	preprocessors: ['tokens-studio'],
	platforms: {
		scss: {
			buildPath: 'src/assets/styles/style-dictionary/',
			files: [
				{
					destination: 'styles-mixins.scss',
					format: 'scss/mixins-styles',
					filter: semanticFilter('tokens/styles/**/*.json')
				}
			],
			options: {
				fileHeader: 'token-header'
			}
		}
	}
};

const logConfig = {
	log: {
		warnings: logWarningLevels.disabled, // 'warn' | 'error' | 'disabled'
		verbosity: logVerbosityLevels.default, // 'default' | 'silent' | 'verbose'
		errors: {
			brokenReferences: logBrokenReferenceLevels.throw // 'throw' | 'console'
		}
	}
};

// Build all configurations
async function build() {
	console.log('Building core tokens...');
	const coreSd = new StyleDictionary({
		...coreConfig,
		...logConfig
	});
	await coreSd.buildAllPlatforms();
	
	console.log('Building component tokens...');
	const componentSd = new StyleDictionary({
		...componentsConfig,
		...logConfig
	});
	await componentSd.buildAllPlatforms();

	console.log('Building dark theme tokens...');
	const darkSd = new StyleDictionary({
		...darkConfig,
		...logConfig
	});
	await darkSd.buildAllPlatforms();

	console.log('Building light theme tokens...');
	const lightSd = new StyleDictionary({
		...lightConfig,
		...logConfig
	});
	await lightSd.buildAllPlatforms();

	console.log('Building styles tokens...');
	const stylesSd = new StyleDictionary({
		...stylesConfig,
		...logConfig
	});
	await stylesSd.buildAllPlatforms();

	console.log('Token build complete!');
}

build();
