import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineCustomElements } from '@kelvininc/ui-components/loader';
import {
	KvActionButton,
	KvActionButtonIcon,
	KvActionButtonSplit,
	KvActionButtonText,
	KvBadge,
	KvBreadcrumb,
	KvBreadcrumbItem,
	KvBreadcrumbList,
	KvSelectOption,
	KvSelect,
	KvDropdown,
	KvSingleSelectDropdown,
	KvMultiSelectDropdown,
	KvIllustration,
	KvLink,
	KvLoader,
	KvRadio,
	KvStateIndicator,
	KvSearch,
	KvIcon,
	KvSwitchButton,
	KvTabItem,
	KvTabList,
	KvTabNavigation,
	KvTagLetter,
	KvTextField,
	KvToaster,
	KvTooltip,
	KvSummaryCard,
	KvRadioButton,
	KvRadioButtonGroup,
	KvInfoLabel,
	KvTreeItem,
	KvTree,
	KvFormHelpText,
	KvFormLabel
} from './stencil-generated/component';

defineCustomElements(window);

const COMPONENTS = [
	KvActionButton,
	KvActionButtonIcon,
	KvActionButtonText,
	KvActionButtonSplit,
	KvBadge,
	KvSwitchButton,
	KvIllustration,
	KvLink,
	KvBreadcrumb,
	KvBreadcrumbItem,
	KvBreadcrumbList,
	KvLoader,
	KvStateIndicator,
	KvRadio,
	KvIcon,
	KvTagLetter,
	KvTabItem,
	KvTabList,
	KvTabNavigation,
	KvTextField,
	KvTooltip,
	KvSummaryCard,
	KvSearch,
	KvSelectOption,
	KvSelect,
	KvDropdown,
	KvSingleSelectDropdown,
	KvMultiSelectDropdown,
	KvToaster,
	KvRadioButton,
	KvRadioButtonGroup,
	KvInfoLabel,
	KvTreeItem,
	KvTree,
	KvFormHelpText,
	KvFormLabel
];

@NgModule({
	declarations: COMPONENTS,
	exports: COMPONENTS,
	imports: [CommonModule],
	providers: []
})
export class KvUIComponentsModule {}
