export const SCHEMA_FORM_STRINGS = {
	showAllErrors: 'Show all errors',
	errors: 'Errors',
	resetToDefaults: 'Reset to defaults',
	discardChanges: 'Discard changes',
	save: 'Save',
	submit: 'Submit',
	defaultValuePrefix: 'Default: ',
	propertyKey: (name: string) => `${name} key`,
	// Sentence-case copies of core's dropdown strings, which stay title case for other consumers.
	// Supersedes the 2026-10-08 dropdown-labels plan's "no React copy of core strings" rule.
	noDataAvailable: 'No data available',
	noDataAvailableDescription: 'There is no data to display at the moment.',
	clearAll: 'Clear all',
	selectAll: 'Select all',
	all: 'All',
	yes: 'Yes',
	no: 'No',
	items: 'Items',
	properties: 'Properties',
	notSet: 'Not set',
	chooseFile: 'Choose file',
	replaceFile: 'Replace file',
	addFiles: 'Add files',
	fileActionFor: (action: string, name: string) => `${action}: ${name}`,
	emptyFile: 'Empty',
	fileReadFailed: 'Could not read the selected file. Try again.',
	clearSelection: 'Clear selection',
	clearSelectionFor: (name: string) => `Clear selection for ${name}`,
	item: 'Item',
	row: 'row',
	actions: 'Actions',
	required: 'required',
	helpFor: (name: string) => `Help for ${name}`,
	moveUp: (name: string) => `Move ${name} up`,
	moveDown: (name: string) => `Move ${name} down`,
	moveUpLabel: 'Move up',
	moveDownLabel: 'Move down',
	reorder: (name: string) => `Reorder ${name}`,
	itemActions: (name: string) => `Actions for ${name}`,
	remove: (name: string) => (name ? `Remove ${name}` : 'Remove'),
	add: (name: string) => `Add ${name}`,
	addItem: (name?: string) => (name ? `Add item to ${name}` : 'Add item'),
	addProperty: (name?: string) => (name ? `Add property to ${name}` : 'Add property'),
	download: (name: string) => `Download ${name || 'file'}`
} as const;
