export const SCHEMA_FORM_STRINGS = {
	notSet: 'Not set',
	chooseFile: 'Choose file',
	replaceFile: 'Replace file',
	addFiles: 'Add files',
	fileActionFor: (action: string, name: string) => `${action}: ${name}`,
	emptyFile: 'Empty',
	fileReadFailed: 'Could not read the selected file. Try again.',
	clearSelection: 'Clear selection',
	clearSelectionFor: (name: string) => `Clear selection for ${name}`,
	item: 'Item',
	row: 'row',
	actions: 'Actions',
	required: 'required',
	helpFor: (name: string) => `Help for ${name}`,
	moveUp: (name: string) => `Move ${name} up`,
	moveDown: (name: string) => `Move ${name} down`,
	moveUpLabel: 'Move up',
	moveDownLabel: 'Move down',
	reorder: (name: string) => `Reorder ${name}`,
	itemActions: (name: string) => `Actions for ${name}`,
	remove: (name: string) => (name ? `Remove ${name}` : 'Remove'),
	add: (name: string) => `Add ${name}`,
	addItem: (name?: string) => (name ? `Add item to ${name}` : 'Add item'),
	addProperty: (name?: string) => (name ? `Add property to ${name}` : 'Add property'),
	download: (name: string) => `Download ${name || 'file'}`
} as const;
