/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PkActionButtonType } from "./components/action-button/action-button.types";
export namespace Components {
    interface ActionButton {
        "buttonClass": string;
        "buttonId": string;
        "enabled": boolean;
        "fixedWidth": number;
        "icon": string;
        "smallSize": boolean;
        "text": string;
        "type": PkActionButtonType;
    }
}
declare global {
    interface HTMLActionButtonElement extends Components.ActionButton, HTMLStencilElement {
    }
    var HTMLActionButtonElement: {
        prototype: HTMLActionButtonElement;
        new (): HTMLActionButtonElement;
    };
    interface HTMLElementTagNameMap {
        "action-button": HTMLActionButtonElement;
    }
}
declare namespace LocalJSX {
    interface ActionButton {
        "buttonClass"?: string;
        "buttonId"?: string;
        "enabled"?: boolean;
        "fixedWidth"?: number;
        "icon"?: string;
        "onButtonClick"?: (event: CustomEvent<MouseEvent>) => void;
        "smallSize"?: boolean;
        "text"?: string;
        "type": PkActionButtonType;
    }
    interface IntrinsicElements {
        "action-button": ActionButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "action-button": LocalJSX.ActionButton & JSXBase.HTMLAttributes<HTMLActionButtonElement>;
        }
    }
}
